### ISSUE TITLE
Whatsapp template shows the image path

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#115]
![Screenshot_20240202_104918](https://github.com/antonym8/Team-app/assets/142376069/a8abd7f5-53e4-432c-88a4-6502e38ac753)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
Not fixed

![Screenshot_20240212_170633](https://github.com/antonym8/Team-app/assets/142376069/697d07c9-6d14-4098-853e-ee830141e421)

**Comment by m8brindakumar** [comment]
its fixed
