### ISSUE TITLE
Update polling -> Double tap

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#150]
Some static screens shows in background

https://github.com/antonym8/Team-app/assets/142376069/3eb740bf-0cde-4c8e-945a-0d0ebb2e22ac

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
Not fixed


https://github.com/antonym8/Team-app/assets/142376069/8385e9cb-2b31-40b1-b77b-93b6aa4dee70

**Comment by m8brindakumar** [comment]
Fixed
