### ISSUE TITLE
First letter should be capital

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#156]
![Screenshot_20240213_114557](https://github.com/antonym8/Team-app/assets/142376069/17611f74-f41e-49e3-8c5f-5320041d4435)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
In edit page not fixed

![Screenshot_20240219_151134](https://github.com/antonym8/Team-app/assets/142376069/32d231a8-0a98-42e7-8f95-990ef0165943)

**Comment by m8brindakumar** [comment]
Fixed
