### ISSUE TITLE
Campaign -> Null value

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#163]
Null value displayed when two options not selected

![Screenshot_20240220_131500](https://github.com/antonym8/Team-app/assets/142376069/050d4ff8-c28c-4e60-8733-6bddfc738707)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
Not fixed

![Screenshot_20240222_160744](https://github.com/antonym8/Team-app/assets/142376069/4bb3cb07-7eff-4ab2-9a6e-dd23d68927e1)

**Comment by m8brindakumar** [comment]
Fixed
