### ISSUE TITLE
Survey -> Gender

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#180]
List page shows gender "Male" but inside gender shows "Others"

![Screenshot_20240220_151308](https://github.com/antonym8/Team-app/assets/142376069/7f90e7d4-bd5a-4f9b-ad9d-1f8e226302c4)
![Screenshot_20240220_151329](https://github.com/antonym8/Team-app/assets/142376069/012fa050-2494-44fb-882d-10e0dec7bae7)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
Not fixed for newly created voters


https://github.com/antonym8/Team-app/assets/142376069/78e359f6-28c9-4be5-93c2-5829a00bbfa8

**Comment by m8brindakumar** [comment]
Fixed
