### ISSUE TITLE
Update voters availability without select the checkboxes

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#46]
Empty toast message displayed when update voters availability without select any checkboxes

![Screenshot_20231222_105657](https://github.com/antonym8/Team-app/assets/142376069/6b1766cc-d68f-4e90-8f19-eee983885c2e)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
Spelling should be voter's

![Screenshot_20231229_104929](https://github.com/antonym8/Team-app/assets/142376069/37c59be9-436b-4efe-834b-5fba993c2fcf)

**Comment by m8brindakumar** [comment]
Fixed

**Comment by antonym8** [comment]
Not fixed

![Screenshot_20240219_182721](https://github.com/antonym8/Team-app/assets/142376069/4e568395-e351-47d2-b452-4653167343c7)

**Comment by m8brindakumar** [comment]
Fixed
