### ISSUE TITLE
Update print format page not working

### ISSUE THREAD

**Issue by antonym8** [antonym8/Team-app#74]
Page have the static data

![Screenshot_20231229_120336](https://github.com/antonym8/Team-app/assets/142376069/0a290a15-ad84-48ce-b750-df597d2066a6)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
Uploaded image's location displayed
Incorrect error message displayed when submit without select the checkboxes

![Screenshot_20240123_111007](https://github.com/antonym8/Team-app/assets/142376069/8bc7b4b1-9d86-4b18-8ef7-45b749b16048)

**Comment by m8brindakumar** [comment]
fixed

**Comment by antonym8** [comment]
Not fixed

![Screenshot_20240212_165507](https://github.com/antonym8/Team-app/assets/142376069/b3ce3324-c4a7-4c9f-857d-6c098a099421)

**Comment by m8brindakumar** [comment]
fixed
